WAKE_WORD = "jarvis"

VOICE_RATE = 180
VOICE_VOLUME = 1.0

LISTEN_TIMEOUT = 6
PHRASE_TIME_LIMIT = 6
AMBIENT_DURATION = 0.6
PAUSE_THRESHOLD = 0.5
NON_WAKE_HIDE_DELAY_MS = 250
UI_FADE_STEP = 0.18
UI_FADE_INTERVAL_MS = 12

UI_TITLE = "JARVIS"
UI_WIDTH = 420
UI_HEIGHT = 200

UI_HIDE_DELAY_MS = 4000
MIC_RECOVERY_DELAY = 2.0
ENABLE_TRAY = True

AI_MODEL = "claude-sonnet-4-6"
AI_MAX_TOKENS = 512
AI_API_KEY_ENV = "ANTHROPIC_API_KEY"  # set this environment variable, do not hardcode the key
